[bar.default]
background_opacity = 0.75
center = ["clock", "media"]
end = [
  "tray",
  "nightlight",
  "battery",
  "bluetooth",
  "privacy",
  "noctalia/screen_recorder:recorder",
  "volume",
  "brightness",
  "control-center",
]
start = ["workspaces", "active_window"]
widget_spacing = 8

[brightness]
enable_ddcutil = true

[calendar]
enabled = true

[control_center]
sidebar = "full"
width = 800

[hot_corners]
enabled = false

[idle]
pre_action_fade_seconds = 5

[location]
auto_locate = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
  "lockscreen-login-box@DP-3",
  "lockscreen-widget-0000000000000001",
]

[lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
box_height = 176.0
box_width = 400.0
cx = 1536.0
cy = 240.0
output = "DP-3"
placement_height = 1280.0
placement_width = 3072.0
rotation = 0.0
type = "clock"

[nightlight]
enabled = true
temperature_night = 4501

[notification]
history_retention_hours = 2
keep_dismissed_in_history = true

[osd]
background_opacity = 0.75
offset_y = 20
position = "bottom_center"

[plugin_settings."noctalia/screen_recorder"]
copy_to_clipboard = true
video_bitrate_mode = "vbr"
video_codec = "hevc"

[plugins]
enabled = ["noctalia/screen_recorder"]

[shell]
avatar_path = "/home/markus/nas/home/onedrive/mrksr/avatar_lemming_upscayled_4x.png"
clipboard_enabled = false
font_family = "Liberation Sans"
niri_overview_type_to_launch_enabled = true
password_style = "random"
polkit_agent = true
popup_borders = false

[shell.launcher]
pinned = [
  "io.element.Element",
  "zen-browser-twilight",
  "chrome-mpoampnhehaaibinfnfeeblpclklpjko-Default",
  "chromium",
  "steam",
]

[shell.panel]
control_center_placement = "floating"
control_center_position = "top_right"
launcher_placement = "floating"
polkit_placement = "floating"
polkit_position = "center"
session_placement = "floating"
session_position = "center"
transparency_mode = "soft"

[theme]
mode = "light"
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

[theme.templates]
builtin_ids = ["niri"]

[wallpaper]
directory = "/home/markus/Pictures/Wallpapers"
edge_smoothness = 0.050000000000000003
fill_color = "#000000"
transition = ["fade", "disc", "stripes", "wipe", "pixelate", "honeycomb"]

[wallpaper.default]
path = "/home/markus/Pictures/Wallpapers/wallhaven_e83mro.jpg"

[widget.active_window]
max_length = 300.0
title_scroll = "on_hover"
type = "active_window"

[widget.battery]
display_mode = "graphic"
type = "battery"

[widget.clock]
format = "{:%a %d %b, %H:%M}"
tooltip_format = "{:%a %d %b, %H:%M}"
type = "clock"
vertical_format = """{:%H
%M}"""

[widget.media]
artist_first = true
hide_when_no_media = true
max_length = 300.0
title_scroll = "on_hover"
type = "media"

[widget.privacy]
hide_inactive = true
type = "privacy"

[widget.tray]
hidden = ["nm-applet"]
hide_passive = false
type = "tray"

[widget.workspaces]
labels_only_when_occupied = true
max_label_chars = 2
pill_scale = 0.9
type = "workspaces"
