[options]
bootstrap_after = 'mrksr#after'
buffer_index_type = 4
colorscheme = 'base16-railscasts'
colorscheme_bg = 'dark'
enable_guicolors = true
enable_statusline_mode = false
enable_tabline_filetype_icon = true
relativenumber = false
snippet_engine = 'ultisnips'
statusline_inactive_separator = 'arrow'
statusline_separator = 'arrow'


# Custom plugins
[[custom_plugins]]
name = 'chriskempson/base16-vim'
merged = 0

[[custom_plugins]]
name = 'Konfekt/Fastfold'
merged = 0

[[custom_plugins]]
name = 'tpope/vim-eunuch'
merged = 0


# Layers
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = 'complete'
auto-completion-tab-key-behavior = 'smart'

[[layers]]
name = 'core#tabline'
enable = false

[[layers]]
name = 'core#statusline'
enable = false

[[layers]]
name = 'fzf'

[[layers]]
name = 'edit'

[[layers]]
name = 'git'

[[layers]]
name = 'lang#dockerfile'

[[layers]]
name = 'lang#ipynb'

[[layers]]
name = 'lang#latex'

[[layers]]
name = 'lang#markdown'

[[layers]]
name = 'lang#python'

[[layers]]
name = 'lang#sh'

[[layers]]
name = 'lang#vim'

[[layers]]
name = 'lang#extra'

[[layers]]
name = 'tmux'
