---
:editor: vim
:thread_by_subject: false
:edit_signature: false
:ask_for_from: false
:ask_for_to: false
:ask_for_cc: false
:ask_for_bcc: false
:ask_for_subject: false
:account_selector: true
:confirm_no_attachments: true
:confirm_top_posting: true
:jump_to_open_message: true
:discard_snippets_from_encrypted_messages: false
:load_more_threads_when_scrolling: true
:default_attachment_save_dir: ''
:sent_source: sup://sent
:archive_sent: true
:poll_interval: 300
:wrap_width: 0
:slip_rows: 0
:col_jump: 2
:stem_language: english
:sync_back_to_maildir: true
:continuous_scroll: true
:always_edit_async: false
:accounts:
  :default:
    :name: Markus Kaiser
    :email: markus@zfix.org
    :alternates:
    - markus.kaiser@in.tum.de
    - mkaiser@kth.se
    - markus.kaiser@tum.de
    - tutor@zfix.org
    - pub@zfix.org
    - game@zfix.org
    :sendmail: "msmtp -t --read-envelope-from"
    :signature: "/home/markus/.signature"
    :gpgkey: ''
