[tools]
bat = "latest"
bottom = "latest"
chezmoi = "latest"
delta = "latest"
duf = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
jq = "latest"
ripgrep = "latest"
starship = "latest"
uv = "latest"
yq = "latest"
