#!/usr/bin/env bash

# see https://github.com/guyzmo/notmuch-abook/
# first update notmuch-abook
for file in $(notmuch search --output=files tag:new) ; do
    cat $file | $HOME/.notmuch-abook update
done

# hack for astroid: mark every new mail as relevant
notmuch tag +astroidhack -- tag:new
# toggle read state for relevant mail I read in astroid
notmuch tag +unread +astroidread -- tag:astroidhack AND NOT tag:unread
notmuch tag -unread -astroidread -astroidhack -- tag:astroidread

# remove new tags
notmuch tag -new -- tag:new
