#!/usr/bin/env bash

# see https://github.com/guyzmo/notmuch-abook/
# first update notmuch-abook
for file in $(notmuch search --output=files tag:new) ; do
    cat $file | $HOME/.notmuch-abook update
done

# ignore spam stuff
notmuch tag -unread -inbox -- tag:spam

# remove new tags
notmuch tag -new -- tag:new
