#!/bin/zsh

<<< 3200000 sudo tee /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq > /dev/null
<<< 3200000 sudo tee /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq > /dev/null
<<< 3200000 sudo tee /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq > /dev/null
<<< 3200000 sudo tee /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq > /dev/null
<<< $1 sudo tee /sys/devices/system/cpu/intel_pstate/max_perf_pct > /dev/null
